apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: karampok/dnsconfig-injector
deploy:
  kubectl:
    manifests:
      - k8s/configmap.yaml
      - k8s/deployment.yaml
      - k8s/service.yaml
